-d C:\Users\stanr\Documents\SR-CRT\FPGA\CRT_Test\impl\gwsynthesis\CRT_Test.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\stanr\Documents\SR-CRT\FPGA\CRT_Test\src\CRT_Test.cst
-cfg C:\Users\stanr\Documents\SR-CRT\FPGA\CRT_Test\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
